In [1]:
import numpy as np


In [2]:
# Creating array
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [3]:
# arange() function
arr2 = np.arange(1,10)
print(arr2)
np.amax([1,2,3,4,5,6,7])

[1 2 3 4 5 6 7 8 9]


7

In [4]:
# ones,zeros
arr3 = np.ones(6)
print(arr3)
arr4 = np.zeros(6)
print(arr4)

[1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0.]


In [5]:
arr5 = np.linspace(1,10,20)
arr5

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [6]:
# 2D array
arr6 = np.zeros((3,3))
print(arr6)

# reshape() function
arr7 = np.arange(1,31).reshape(6,5)
print(arr7)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [7]:
arr8 = np.random.randint(1,10,6)
print(arr8)

arr9 = np.random.randint(1,11,(2,6))
print(arr9)

[7 1 4 8 8 3]
[[ 4  8  1  4  8  5]
 [10  7  9  1  7  6]]


In [8]:
arr10 = np.arange(1,61).reshape((6,10))
print(arr10)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [9]:
print(arr10.shape)
print(arr10.dtype)
print(arr10.ndim)
print(arr10.size)

(6, 10)
int32
2
60


In [10]:
# they both are used to covert higher order array to 1D
arr10.flatten()
arr10.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [11]:
arr11 = arr9.T
arr11

array([[ 4, 10],
       [ 8,  7],
       [ 1,  9],
       [ 4,  1],
       [ 8,  7],
       [ 5,  6]])

In [12]:
# Accessing and slicing in arrays
## IN 1D
arr12 = np.arange(1,11)
arr12[9]=11
arr12
print(arr12[2:8])

## In 2D
arr13 = np.arange(1,21).reshape(5,4)
arr13
arr13[1]
arr13[1][3]
print(arr13[0:2,0:4])
print(arr13[:1,1])
arr13[-1:-3][-3:-1]

[3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[2]


array([], shape=(0, 4), dtype=int32)

In [13]:
# Creating a 3D array

arr14 = np.random.randint(1,10,(6,2,3))
arr14

array([[[9, 2, 3],
        [3, 7, 2]],

       [[1, 2, 1],
        [2, 9, 5]],

       [[5, 6, 4],
        [1, 2, 3]],

       [[2, 3, 7],
        [7, 1, 5]],

       [[6, 6, 2],
        [6, 4, 6]],

       [[5, 3, 3],
        [3, 9, 6]]])

In [14]:
arr15 = np.arange(1,21).reshape(5,2,2)
print(arr15)

arr15[0:2,0:1,]
arr15[0:5,0,1]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


array([ 2,  6, 10, 14, 18])